AnalogStudiosRI/www.analogstudios.net

- README.md
- package.json
N / A
1. Renamed org from _Analog-Studios_ -> AnalogStudiosRI
> update per org rename

- greenwood.config.js
- package.json
- yarn.lock
N / A
1. Adds [**rollup-plugin-analyzer**](https://www.npmjs.com/package/rollup-plugin-analyzer)
1. Adds [**rollup-plugin-visualizer**](https://github.com/btd/rollup-plugin-visualizer)
> add bundle visualizer plugin

- .eslintrc.js
- package.json
- src/index.html
- src/index.js
- src/routes/home.js
- yarn.lock
N / A
1. introduces Single Page Application (SPA) framework
> Needs https://github.com/ProjectEvergreen/greenwood/pull/672 merged
> introduce SPA routing

- greenwood.config.js
- package.json
- yarn.lock
git status
resolves #26 
1. Adopt [npm published version of this](https://github.com/AnalogStudiosRI/greenwood-plugin-font-awesome) as a plugin
> adopt published version of font awesome greenwood plugin

- src/services/artists-service.js
N / A (Trello)
Inactive artists in the database should not be shown on the website.
> hide inactive artists from artists servivce response

- src/components/card/card.js
- src/routes/artists/artists.js
N / A (Trello)
1. Reverse sort artists so newer albums are at the top of the page
1. Promote Analog as always at the top
> artists page relevancy enhancements

- src/routes/home/home.css
resolves issue #22 
1. [x] fixed banner spacing
1. [x] fixed transparency on labels
> fix spacing and styles on homepage banner

- src/routes/albums/album-details.js
- src/routes/albums/albums.css
- src/routes/artists/artist-details.js
- src/routes/events/event-details.js
- src/routes/events/events.css
- src/services/albums-service.js
- src/services/events-service.js
resolves #31 
1. Artist Details Page
1. Album Details Page
1. Event Details Page
1. [x] Album Details Page
1. [x] Interact and Share Bar - deferred to https://github.com/AnalogStudiosRI/www.analogstudios.net/issues/39
1. [x] Event Details Page
1. [x] Misc styling (download link styles / mobile responsiveness check - see #42 )
> Details Pages

- src/index.html
> fix meta description 

- src/components/header/header.css
- src/components/header/header.js
- src/components/navigation/navigation.css
- src/index.html
resolves issue #21 
Updated header and navigation components styles and some structure to better match original version.
> fix header styles

- src/routes/events/event-details.js
- src/routes/events/events.css
- src/routes/events/events.js
> fix events page styling

- src/components/header/header.css
- src/components/navigation/navigation.css
- src/routes/home/home.css
- src/routes/home/home.js
revert header color to original
make content responsive
> fix homepage landing styles

- src/index.html
- src/index.ts
- src/routes/contact/contact.css
- src/routes/contact/contact.ts
resolves #29 ([production page](https://www.analogstudios.net/contact) for reference)
1. Integrated Netlify forms following [this guide](https://www.netlify.com/blog/2017/07/20/how-to-integrate-netlifys-form-handling-in-a-react-app/) and modeled it after the _"Form Handling with a Stateless React Form"_ example
(will take care of background styling in another issue)
~~Will need to test in Netlify to see if it works.~~
> initial implementation of netlify form

- src/styles.css
#12 
1. Added solid secondary background to all pages
1. Added a little content padding to all pages
> solid page content background and some padding for content

- greenwood.config.js
- package.json
- src/routes/albums/album-details.ts
- src/routes/albums/albums.ts
- src/routes/artists/artist-details.ts
- src/routes/artists/artists.ts
- src/routes/contact/contact.ts
- src/routes/events/event-details.ts
- src/routes/events/events.ts
- src/routes/home/home.ts
- yarn.lock
resolves #25 (_just_ for the home page - see https://github.com/AnalogStudiosRI/www.analogstudios.net/issues/25#issuecomment-1007092408)
1. Restored GA just for the home page
1. [x] Filter only for prod domains
1. [x] Do all pages after #66
> restore basic GA integration

- src/routes/contact/contact.css
Contact form was overflowing on mobile
1.  Added CSS to constrain the contact form
> constrain contact form for mobile

- src/routes/home/home.ts
- src/services/events/events-service.ts
#13 and dependent on work in https://github.com/AnalogStudiosRI/api
Known issues
- (blocking) https://github.com/AnalogStudiosRI/api/issues/4
- https://github.com/AnalogStudiosRI/api/issues/5
1. Convert events to serverless + Contentful API (WIP)
1. Create new endpoint and integrate into app
1. [x] Modeled data
1. [x] Backport data
1. [x] Get Event by ID
1. [x] Integrate into app
> integration of events API v2 from Contentful

- src/routes/contact/contact.css
resolves #77 
1.  `20%` left padding seems to do the trick?
----
Should test on mobile / responsive ranges too.
> add padding to contact form

- src/routes/albums/album-details.ts
resolves #83 
1. Add release year to album details page
> display album release year on album details page

- package.json
- yarn.lock
Resolves #92
- Added `@types/google.analytics` to add typings for `ga` function
> added @types/google.analytics to resolve ga types

- package-lock.json
- package.json
- src/components/social-share/social-share.ts
resolves #106 
1. Upgrade to latest version of **web-social-share**
1. define social share component per [latest README docs](https://www.npmjs.com/package/web-social-share)
> bug: #106 fix social share component
